- name:  copy_file_and_reload
  hosts: all
  user: root
  gather_facts:  false
  vars:
      target_path: /App/prometheus/sd
  tasks:

      - name: mkdir
        file: path={{ target_path }} state=directory
        async: 5
        poll: 0


      - name: copy target file
        copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root
          group: root
          mode: 0644
          force: true

        with_items:
          - { src: './{{ src_sd_file_name }}', dest: '{{ target_path }}/{{ dest_sd_file_name }}' }
#        async: 10
#        poll: 0

      - name: reload_service
        uri:
          url: http://localhost:{{ service_port }}/-/reload
          timeout: 5
          method: POST
          status_code: 200
          return_content: yes
        async: 5
        poll: 0
        register: result
