shard_service:
  scrape_prome_test:
    nodes:
      - localhost
    port: 9091
    dest_sd_file_name: test_file_sd_by_prome_shared.json
    yaml_path: copy_file_and_reload_prome.yaml

job_setting:
  ticker_interval: 600

http:
  port: 8801

consul:
  host: localhost
  port: 8500
